#
# Copyright (c) 2015 Bosch Software Innovations GmbH and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Spring cloud stream events configuration, enable if remote events are needed between services
org.eclipse.hawkbit.events.remote-enabled=false
org.eclipse.hawkbit.events.remote-fanout-channel-out=fanoutChannel-out-0
org.eclipse.hawkbit.events.remote-grouped-channel-out=groupedChannel-out-0


# fanaoutBus used for events for all replicas - e.g. cache invalidation
spring.cloud.stream.bindings.fanoutChannel-in-0.destination=fanoutChannel
spring.cloud.stream.bindings.fanoutChannel-out-0.destination=fanoutChannel

# groupedBus used for events for a single replica of a kind - e.g. event to be processed by a single replica of kind
spring.cloud.stream.bindings.groupedChannel-in-0.destination=groupedChannel
spring.cloud.stream.bindings.groupedChannel-out-0.destination=groupedChannel

# Spring cloud bus and stream END